version: 2
jobs:
  build:
    working_directory: ~/fairy
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run:
          name: "Get Enviroment"
          command: |
            echo $JIRO_USER
            echo $JIRO_PASSWORD
            echo $KEYID
            echo $KEY_SET
      - run: mkdir ~/.gnupg
      - run: echo "disable-ipv6" >> /home/circleci/.gnupg/dirmngr.conf
      - run: gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys $KEYID
      - run: gpg --list-keys
      - run: mvn clean install -Psign-artifacts
      - run: mvn release:prapare
      - run: mvn release:perform
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/fairy-0.0.2-SNAPSHOT.jar
workflows:
  version: 2
  workflow:
    jobs:
      - build

